version: '3'

services:
  db:
    container_name: whichisp-postgres
    image: postgres:12.5-alpine
    restart: always
    ports:
      - 5432:5432
    volumes: 
      - db_data:/var/lib/postgresql/data/
    env_file:
      - db.env
  app:  
    container_name: whichisp-frontend
    # command: npm start
    command: npm start && tail -f /dev/null
    restart: always
    build: ./app
    image: whichisp:latest
    volumes:
      - ./app/src:/usr/whichisp/src
      - ./app/views:/usr/whichisp/views
      - ./app/public:/usr/whichisp/public
      - ./app/config:/usr/whichisp/config
      # - ./app/node_modules:/usr/whichisp/node_modules
    ports:
      - "3000:3000"
    env_file: 
      - db.env
    links:
      - db
    depends_on:
      - db

volumes:
  db_data: